apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: riverbed-operator-metrics-auth-rolebinding
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: riverbed-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: riverbed-operator-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: riverbed-operator-controller-manager
  namespace: {{ .Values.namespace }} 