apiVersion: v1
kind: Service
metadata:
  name: riverbed-operator-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: riverbed-operator
    control-plane: controller-manager
spec:
  ports:
    - name: https
      port: {{ .Values.service.metricsPort }}
      protocol: TCP
      targetPort: {{ .Values.service.metricsPort }}
  selector:
    control-plane: controller-manager 