apiVersion: v1
kind: ServiceAccount
metadata:
  name: riverbed-operator-controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: riverbed-operator 